// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ForecastHandler is an autogenerated mock type for the ForecastHandler type
type ForecastHandler struct {
	mock.Mock
}

// HandleForecastRequest provides a mock function with given fields: w, r
func (_m *ForecastHandler) HandleForecastRequest(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewForecastHandler creates a new instance of ForecastHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForecastHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForecastHandler {
	mock := &ForecastHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
